spring:
  datasource:
    url: jdbc:h2:file:./localdb;NON_KEYWORDS=USER;AUTO_SERVER=TRUE # DB 접속 URL
    username: sa # DB 접속 username
    password: # DB 접속 password, 없음
    driver-class-name: org.h2.Driver # DB 접속 드라이버
  messages:
    basename: i18n/exception
    encoding: UTF-8
  h2.console:
    enabled: true # 콘솔 사용 여부, 로컬에서 웹 브라우저로도 접속 가능
  jpa:
    hibernate:
      ddl-auto: create # DDL 자동 생성
    properties:
      hibernate:
        format_sql: false # SQL 로그 출력
  mvc:
    path-match:
      matching-strategy: ant-path-matcher # ant 방식의 URL 매칭 사용
logging:
  level:
    org:
      hibernate:
        SQL: debug # SQL 로그 출력을 위한 로그 레벨 조정

mybatis:
  mapper-locations: classpath:mapper/*.xml # MyBatis Mapper 위치
  type-aliases-package: com.wdyj.boilerplate.mapper # MyBatis Mapper 패키지 위치
